#!/bin/bash
# This scripts add all DOCENTI listed below using the add_DOCENTE_2_rstudio.sh script.
# Please, consider to configure add_DOCENTE_2_rstudio.sh before to run THIS script.


container="rstudio_didattica_mgs"
PSWD="mgs2023"

# ==== DOCENTI ====
# Giuliano Langella
#echo "Giuliano.Langella"
#./add_USER_2_rstudio.sh Giuliano.Langella antonietta $container 3002
# ==== DOCENTI ====


# ==== STUDENTI ====
declare -a Students=(
Giuseppe.DellaFera
LUISA.ARRO
PAOLO.FALCHETTI
ELEONORA.CAGLIERO
LUCIO.DEBENEDICTIS
MILENA.BRAGADINI
SILVIAMARIA.STEFANELLI
LORENZO.TERRAROLI
BENEDETTA.VERGA
VIRGINIA.VONA
MATTIAANDREA.RUDINI
MICHELE.DELVECCHIO
STEFANIA.VOLANI
THOMAS.ROSSI
JACOPO.LEARDI
MATTEO.TONELLO
FRANCESCO.GIUNCO
JODIE.PAVAN
SARA.BORSOI
ANDREAALICE.CARPANI
LEONARDO.CANFAILLA
JOHNNY.NICOLIS
GIULIA.VALLONE
FEDERICA.MURO
ILARIA.RINALDI
EDOARDO.PIVA
BEATRICE.FRABETTI
EDDA.PATTUZZI
ANDREA.MENGHETTI
ALESSANDRO.ORLANDINI
FRANCESCA.CHIAPPA
GIOVANNI.GATTI
BENEDETTA.GORI
LORENZO.ORTOLANI
GIACOMO.GROSSO
VALERIO.COTTURONE
NOEMI.BARONE
ANTONIO.DIMATTEO
ROBERTA.NARCISI
ANNACHIARA.ROSATI
ANTONIO.NIGRO
THOMAS.VATRANO
EMANUELEDANIELE.BOSCO
FELIXDANTE.DERENZINSHULLA
)

for Student in ${Students[@]} 
 do
  echo "$Student"
  ./add_USER_2_rstudio.sh $Student $PSWD $container
done
# ==== STUDENTI ====
