require(sf)
point=st_point(c(14.502340,40.834738))
class(point)
geom=st_sfc(point, crs=4326)
Name=c("Federico")
Surname=c("Ambrosio")
SchoolName=c("LuigiEinaudi")
GraduationDate=c(2016)
attrib=data.frame(Name,Surname,SchoolName,GraduationDate)
attrib
SF4=st_sf(attrib, geometry=geom)
class(SF4)
