library(sf)
library(dplyr)
point= st_point(c(14.345695674419401, 40.84060180199219))
Name= c("Federica")
Surname= c("Pinto")
SchoolName= c("Liceo Scientifico Carlo Urbani")
GraduationDate= c("2014")
mydata= data.frame(Name, Surname, SchoolName, GraduationDate)
mydata
# st_crs(4326)
geom=st_sfc(point, crs = 4326)
st_crs(geom)
SF3=st_sf(mydata,geom)
sf
getwd()
setwd("~/Federica Pinto")
liceo_curb= st_read("liceocurbani.geojson")
plot(liceo_curb, col="blue")
library(tmap)
tmap_mode("view")
tm_shape(liceo_curb) + tm_dots(col = "blue",title = "Liceo Urbani", size = 0.1)

